import type { Employee, Department, LeaveRequest, Absence } from "./types"

export const mockDepartments: Department[] = [
  {
    id: "1",
    name: "Ressources Humaines",
    manager: "Marie Dubois",
    employeeCount: 8,
    color: "#2d5a5a",
  },
  {
    id: "2",
    name: "Développement",
    manager: "Ahmed Benali",
    employeeCount: 15,
    color: "#f4a261",
  },
  {
    id: "3",
    name: "Marketing",
    manager: "Fatima Zahra",
    employeeCount: 6,
    color: "#e76f51",
  },
  {
    id: "4",
    name: "Finance",
    manager: "Youssef Alami",
    employeeCount: 4,
    color: "#2a9d8f",
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "1",
    cin: "AB123456",
    cnss: "123456789",
    firstName: "Marie",
    lastName: "Dubois",
    email: "marie.dubois@rivolio.fr",
    phone: "+212 6 12 34 56 78",
    department: "Ressources Humaines",
    position: "Directrice RH",
    contractType: "CDI",
    startDate: "2022-01-15",
    salary: 25000,
    status: "ACTIF",
  },
  {
    id: "2",
    cin: "CD789012",
    cnss: "987654321",
    firstName: "Ahmed",
    lastName: "Benali",
    email: "ahmed.benali@rivolio.fr",
    phone: "+212 6 98 76 54 32",
    department: "Développement",
    position: "Lead Developer",
    contractType: "CDI",
    startDate: "2021-03-10",
    salary: 22000,
    status: "ACTIF",
  },
  {
    id: "3",
    cin: "EF345678",
    cnss: "456789123",
    firstName: "Fatima",
    lastName: "Zahra",
    email: "fatima.zahra@rivolio.fr",
    phone: "+212 6 11 22 33 44",
    department: "Marketing",
    position: "Chef Marketing",
    contractType: "CDI",
    startDate: "2022-06-01",
    salary: 18000,
    status: "ACTIF",
  },
  {
    id: "4",
    cin: "GH901234",
    cnss: "789123456",
    firstName: "Youssef",
    lastName: "Alami",
    email: "youssef.alami@rivolio.fr",
    phone: "+212 6 55 66 77 88",
    department: "Finance",
    position: "Contrôleur Financier",
    contractType: "CDD",
    startDate: "2023-01-01",
    endDate: "2024-12-31",
    salary: 20000,
    status: "ACTIF",
  },
]

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: "1",
    employeeId: "1",
    employeeName: "Marie Dubois",
    department: "Ressources Humaines",
    type: "CONGE_ANNUEL",
    startDate: "2024-02-15",
    endDate: "2024-02-25",
    days: 8,
    reason: "Congés annuels",
    status: "EN_ATTENTE",
    requestDate: "2024-01-20",
  },
  {
    id: "2",
    employeeId: "2",
    employeeName: "Ahmed Benali",
    department: "Développement",
    type: "CONGE_MALADIE",
    startDate: "2024-01-28",
    endDate: "2024-01-30",
    days: 3,
    reason: "Certificat médical",
    status: "APPROUVE",
    requestDate: "2024-01-27",
    approvedBy: "Marie Dubois",
    approvedDate: "2024-01-27",
  },
]

export const mockAbsences: Absence[] = [
  {
    id: "1",
    employeeId: "3",
    employeeName: "Fatima Zahra",
    date: "2024-01-25",
    type: "RETARD",
    duration: 1,
    reason: "Embouteillages",
    justified: true,
  },
  {
    id: "2",
    employeeId: "4",
    employeeName: "Youssef Alami",
    date: "2024-01-24",
    type: "ABSENCE_NON_JUSTIFIEE",
    duration: 8,
    justified: false,
  },
]
